### PR TITLE
NXP-28621: remove 'nuxeoctl mp-init' command call

### PR DESCRIPTION
**Pull request by troger**

### CODE REVIEW

**Review by kevinleturc — APPROVED** [review]

**Review by ataillefer — APPROVED** [review]

**Review by dmetzler — CHANGES_REQUESTED** [review]
Running the `setup.py` does change the 9.10 and 10.10 image definitions. The changes should only affect 11.x image definition.

**Comment by troger** [comment]
@dmetzler should be good now, tell me if I missed something.

**Review by ataillefer — APPROVED** [review]

**Comment by dmetzler** [comment]
So basically, here is what is expected:

```
# git checkout task-NXP-28621-remove-wizard
Switched to branch 'task-NXP-28621-remove-wizard'
Your branch is up to date with 'origin/task-NXP-28621-remove-wizard'.
# ./update.py
Please enter a connect account user: dmetzler
Please enter the connect password:
Generating files for 10.10
Generating files for 8.10
Generating files for 9.10
Generating files for master
# git status
On branch task-NXP-28621-remove-wizard
Your branch is up to date with 'origin/task-NXP-28621-remove-wizard'.

nothing to commit, working tree clean
```

And here is what I have on the last git status:
```
# git status
On branch task-NXP-28621-remove-wizard
Your branch is up to date with 'origin/task-NXP-28621-remove-wizard'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   10.10/Dockerfile
        modified:   10.10/centos/Dockerfile
        modified:   10.10/rhel/Dockerfile
        modified:   9.10/Dockerfile
        modified:   9.10/centos/Dockerfile
        modified:   9.10/rhel/Dockerfile

no changes added to commit (use "git add" and/or "git commit -a")
```
Currently the diff are about a newline at the end of the file. If it's normal, then the change should also be commited. (Basically, running `update.py` should not change anything).

I hope I've been clear enough, and at least this time I did not make a mistake in the name of the python script.

**Comment by troger** [comment]
I've removed the newline.

**Review by dmetzler — APPROVED** [review]

**Pull request merged**
